name: Terraform plan

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    # types: 
    #   - opened

# env:
#   TF_CLOUD_ORGANIZATION: "yandex-cloud"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "learn-terraform-github-actions"
#   CONFIG_DIRECTORY: "./"

jobs: 
  hi_mark:
    runs-on: ubuntu-latest
    steps:
      - name: openning
        run: echo "lets started planning"
