name: Terraform plan

on: 
  pull_request:
    branches:
      - main
    types:
      - opened
  
# env:
#   TF_CLOUD_ORGANIZATION: "yandex-cloud"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "learn-terraform-github-actions"
#   CONFIG_DIRECTORY: "./"

jobs: 
  openning:
    runs-on: ubuntu-latest
    steps:
      - name: openning
        run: echo "lets started planning"
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup TF 
        uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Plan
        run: terraform plan