name: Terraform plan

on:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened
  push:
    branches:
      - test


jobs: 
  if_created:
    runs-on: ubuntu-latest
    steps:
      - name: openning
        run: echo "lets started planning"
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup TF 
        uses: hashicorp/setup-terraform@v3



      - name: IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Plan
        run: |
          terraform init
          terraform validate
          export TF_VAR_yc_iam_token=${{steps.issue-iam-token.outputs}}
          export TF_VAR_cloud_id=${{secrets.YC_CLOUD_ID}}
          export TF_VAR_folder_id=${{secrets.YC_CLOUD_ID}}
          terraform plan