name: Terraform apply

on:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed
  push:
    branches:
      - test


jobs: 
  if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: openning
        run: echo "let's started applying"
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup TF 
        uses: hashicorp/setup-terraform@v3



      - name: IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # - name: setup Yandex Cloud
      #   uses: nightstory/setup-yc@v1
      #   with:
      #     enable-cache: true

      # # Oauth Token ${{secrets.YC_OATH_TOKEN}}
      # - name: register 
      #   run: yc init --jq
      # - name: setting configs
      #   id: oauth-config
      #   run: |
      #     yc config set  --token=true token ${{secrets.YC_OATH_TOKEN}}
      #     yc config list

      - name: Apply
        run: |
          terraform init
          terraform validate
          export TF_VAR_yc_iam_token=${{steps.issue-iam-token.outputs}}
          export TF_VAR_cloud_id=${{secrets.YC_CLOUD_ID}}
          export TF_VAR_folder_id=${{secrets.YC_CLOUD_ID}}
          terraform apply -auto-approve