name: Terraform plan

on:
  pull_request:
    branches:
      - main
    types:
      - opened


jobs: 
  if_created:
    runs-on: ubuntu-latest
    steps:
      - name: openning
        run: echo "let's started planning"
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup TF 
        uses: hashicorp/setup-terraform@v3



      - name: IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Plan
        run: |
          terraform init -backend-config="access_key=${{secrets.BM_ACCESS_KEY}}" -backend-config="secret_key=${{secrets.BM_SECRET_KEY}}"
          terraform validate
          export TF_VAR_yc_iam_token=${{steps.issue-iam-token.outputs.token}}
          export TF_VAR_cloud_id=${{secrets.YC_CLOUD_ID}}
          export TF_VAR_folder_id=${{secrets.YC_FOLDER_ID}}
          terraform plan