name: Terraform apply

on:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed
  push:
    branches:
      - test

# env: 
  

jobs: 
  if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: openning
        run: echo "lets started applying"
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup TF 
        uses: hashicorp/setup-terraform@v3



      - name: IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

           
      - name: setting configs
        run: |
          echo ${{ steps.issue-iam-token.outcome }}
      #     yc config set  --token=true token ${{secrets.YC_OATH_TOKEN}}
      #     yc config set --cloud-id=true cloud-id ${{secrets.YC_CLOUD_ID}}
      #     yc config set --folder-id=true folder-id ${{secrets.YC_FOLDER_ID}}
      #     yc config set compute-default-zone "ru-central1-a"
      #     yc config list



      # - name: Apply
      #   run: |
      #     terraform init
      #     terraform validate
      #     export TF_VAR_yc_iam_token=${{steps.issue-iam-token.outputs}}
      #     export TF_VAR_cloud_id=${{secrets.YC_CLOUD_ID}}
      #     export TF_VAR_folder_id=${{secrets.YC_FOLDER_ID}}
      #     terraform apply -auto-approve