name: Terraform plan

on:
  push:
    branches:
      - test
#   pull_request:
#     branches:
#       - main
#     types:
#       - opened
  
# env:
#   TF_CLOUD_ORGANIZATION: "yandex-cloud"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "learn-terraform-github-actions"
#   CONFIG_DIRECTORY: "./"

jobs: 
  openning:
    runs-on: ubuntu-latest
    steps:
      - name: openning
        run: echo "lets started planning"
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup TF 
        uses: hashicorp/setup-terraform@v3


      - name: setup yc
        uses: nightstory/setup-yc@v1
        with:
          enable-cache: true
      - name: common commands
        run: ls && ps aux && ifconfig

    #   - name: IAM Token
    #     id: issue-iam-token
    #     uses: yc-actions/yc-iam-token@v1
    #     with:
    #       yc-key-id: ${{ secrets.YC_KEY_ID }}
    #       yc-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
    #       yc-private-key: ${{ secrets.YC_PRIVATE_KEY }}
